#include "../../config.h"

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       10

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    90

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      5

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0
